on: [push]

uses: docker/build-push-action@v1
with:
  username: ${{ secrets.DOCKER_USERNAME }}
  password: ${{ secrets.DOCKER_PASSWORD }}
  dockerfile: cloud9/Dockerfile
  repository: denhamparry/cloud9
  tags: latest
